language: bash
sudo: required
dist: trusty
services:
  # - docker
git:
  depth: 1
  submodules: false
branches:
  only:
  - master
# cache:
#   directories:
#     - "node_modules"
env:
  global:
    TECH_HUB_ENV='production'
# addons:
#   ssh_known_hosts: portfolioapi.joshbacon.name
#   ssh_known_hosts: portfolio.joshbacon.name
before_install:
  - echo "Before Install..."
install:
  - echo "Install..."
before_script:
  - echo "Before Script..."
script:
  - echo "Script..."
after_script:
  - echo "After Script..."
before_cache:
  - echo "Before Cache..."
after_success:
  - echo "After Success..."
after_failure:
  - echo "After Failure..."
before_deploy:
  - echo -n ${K8S_CA_CERT} | base64 --decode > ${HOME}/ca.cert
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - | 
    kubectl config set-cluster cluster \
    --certificate-authority=${HOME}/ca.cert \
    --server='https://35.227.175.60' \
    --embed-certs
  - |
    kubectl config set-credentials user \
    --token=$(echo -n ${K8S_TOKEN} | base64 --decode)
  - |
    kubectl config set-context context \
    --cluster='cluster' \
    --user='user' \
    --namespace='default'
  - kubectl config use-context context
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > ${HOME}/get_helm.sh
  - chmod 700 ${HOME}/get_helm.sh
  - source ${HOME}/get_helm.sh  --version 'v2.9.1'
  - helm init --client-only
deploy:
  provider: script
  script: bash ./generate_spec.sh | kubectl apply -f -
  on:
    branch: master
  skip_cleanup: true
after_deploy:
  - kubectl create -f mongodb-init-job-spec.yaml
