---
apiVersion: v1
kind: Service
metadata:
  name: tech-hub-mongodb-replicaset-0-node-port
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32367
    port: 27017
    protocol: TCP
  selector:
    app: mongodb-replicaset
    release: tech-hub
    statefulset.kubernetes.io/pod-name: tech-hub-mongodb-replicaset-0
  type: NodePort
